frigate:
  # Host (without http://), e.g. 192.168.1.100:5000
  frigate_url: "10.5.1.128:5000"
  api_key: ""          # or PLUS_API_KEY for Frigate+
  bearer_token: ""     # if using JWT
  username: ""         # optional: basic auth or to get JWT via /api/login
  password: ""
  # MQTT settings
  mqtt_server: "10.5.1.236"
  main_topic: "frigate"
  mqtt_auth: false
  mqtt_username: ""
  mqtt_password: ""

webui:
  host: "0.0.0.0"
  port: 7767

classification:
  model: "/models/birds_V1_3.tflite"
  labels: "/models/birds_V1_labelmap.txt"
  threshold: 0.3
